'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class maisDODD_Message

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divMainDODDMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divMainDODDMessage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divDODAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDODAdmin As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''vdsAddingMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vdsAddingMessage As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''rfvMessageStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvMessageStartDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rfvMessageEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvMessageEndDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStartDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEndDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ckPriority control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckPriority As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''rfvMessageSubject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvMessageSubject As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtSubject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSubject As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvMessage_Message control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvMessage_Message As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMessage As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblFileUploadText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFileUploadText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''fulMessageDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fulMessageDoc As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''bntUploadDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bntUploadDoc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''grvMessageDocuments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvMessageDocuments As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''grAdminDocumentsInUDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grAdminDocumentsInUDS As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''cvPublicistTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cvPublicistTo As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''ckGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckGroup As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ckPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckPerson As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''trGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trGroup As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''pnlAddGrop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAddGrop As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lstRolesFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstRolesFrom As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''bntAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bntAdd As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''bntRemove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bntRemove As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lstRolesTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstRolesTo As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''ckbGroupSendEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckbGroupSendEmail As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''trPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trPerson As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''pnlAddPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAddPerson As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lstPersonFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstPersonFrom As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''bntAddPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bntAddPerson As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''bntRemovePerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bntRemovePerson As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lstPersonTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstPersonTo As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''ckbPersonSendEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckbPersonSendEmail As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''bntSaveMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bntSaveMessage As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''bntCancelMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bntCancelMessage As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hfMessageID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfMessageID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''dvListOfMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvListOfMessage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''bntNewMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bntNewMessage As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ckbSearchMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckbSearchMessage As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtSearchStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearchStartDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSearchEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearchEndDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bntSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bntSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gvListMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvListMessage As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''dvViewMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvViewMessage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtViewStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtViewStartDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtViewEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtViewEndDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ckViewPriority control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ckViewPriority As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtViewSubject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtViewSubject As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtViewMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtViewMessage As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''grViewUDSDoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grViewUDSDoc As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''bntBackToHomePage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bntBackToHomePage As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As MAIS.Web.MasterPage
        Get
            Return CType(MyBase.Master, MAIS.Web.MasterPage)
        End Get
    End Property
End Class
