'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Address1
    Public Property Address_Sid As Integer
    Public Property Address_Information_Sid As Integer
    Public Property City_Information_Sid As Integer
    Public Property Create_By As Integer
    Public Property Create_Date As Date
    Public Property Last_Update_By As Integer
    Public Property Last_Last_Update_Date As Date

    Public Overridable Property Address_Information As Address_Information
    Public Overridable Property City_Information As City_Information
    Public Overridable Property Application_Address_Xref As ICollection(Of Application_Address_Xref) = New HashSet(Of Application_Address_Xref)
    Public Overridable Property Application_Employer_Address_Xref As ICollection(Of Application_Employer_Address_Xref) = New HashSet(Of Application_Employer_Address_Xref)
    Public Overridable Property Employer_RN_DD_Person_Type_Address_Xref As ICollection(Of Employer_RN_DD_Person_Type_Address_Xref) = New HashSet(Of Employer_RN_DD_Person_Type_Address_Xref)
    Public Overridable Property RN_DD_Person_Type_Address_Xref As ICollection(Of RN_DD_Person_Type_Address_Xref) = New HashSet(Of RN_DD_Person_Type_Address_Xref)
    Public Overridable Property Session_Address_Xref As ICollection(Of Session_Address_Xref) = New HashSet(Of Session_Address_Xref)
    Public Overridable Property RN_Work_Experience_Address_Xref As ICollection(Of RN_Work_Experience_Address_Xref) = New HashSet(Of RN_Work_Experience_Address_Xref)
    Public Overridable Property RN_Application_Work_Experience_Address_Xref As ICollection(Of RN_Application_Work_Experience_Address_Xref) = New HashSet(Of RN_Application_Work_Experience_Address_Xref)

End Class
