'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Address_Information
    Public Property Address_Information_Sid As Integer
    Public Property Building_Name As String
    Public Property Address_Line1 As String
    Public Property Address_Line2 As String
    Public Property Address_Line3 As String
    Public Property Create_By As Integer
    Public Property Create_Date As Date
    Public Property Last_Update_By As Integer
    Public Property Last_Update_Date As Date

    Public Overridable Property Address1 As ICollection(Of Address1) = New HashSet(Of Address1)

End Class
