'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Application_History
    Public Property Application_History_Sid As Integer
    Public Property RN_DD_Person_Type_Xref_Sid As Nullable(Of Integer)
    Public Property Application_Sid As Integer
    Public Property Application_Type_Sid As Integer
    Public Property Role_Category_Level_Sid As Integer
    Public Property Training_CEUS_Date As Nullable(Of Date)
    Public Property DDPersonnel_Skills_Date As Nullable(Of Date)
    Public Property Attestation_Date As Nullable(Of Date)
    Public Property Certification_Printed_Date As Nullable(Of Date)
    Public Property Certification_Sent_Email_Date As Nullable(Of Date)
    Public Property Create_Date As Date
    Public Property Create_By As Integer
    Public Property Last_Update_Date As Date
    Public Property Last_Update_By As Integer
    Public Property RN_License_Or_4SSN As String
    Public Property Attestant_SId As Nullable(Of Integer)

    Public Overridable Property Application_Type As Application_Type
    Public Overridable Property Application_History_Status As ICollection(Of Application_History_Status) = New HashSet(Of Application_History_Status)
    Public Overridable Property RN_DD_Person_Type_Xref As RN_DD_Person_Type_Xref
    Public Overridable Property Role_Category_Level_Xref As Role_Category_Level_Xref

End Class
