'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Application_Attestation
    Public Property Application_Attestation_Sid As Integer
    Public Property Application_Sid As Integer
    Public Property Acceptance_Flg As Boolean
    Public Property Attestation_Sid As Integer
    Public Property Create_Date As Date
    Public Property Create_By As Integer
    Public Property Last_Update_Date As Date
    Public Property Last_Update_By As Integer

    Public Overridable Property Attestation As Attestation
    Public Overridable Property Application As Application

End Class
