'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Application_Type
    Public Property Application_Type_Sid As Integer
    Public Property Application_Code As String
    Public Property Application_Desc As String
    Public Property Active_Flg As Boolean
    Public Property Start_Date As Date
    Public Property End_Date As Date
    Public Property Create_Date As Date
    Public Property Create_By As Integer
    Public Property Last_Update_Date As Date
    Public Property Last_Update_By As Integer

    Public Overridable Property Attestation_Application_Type_Role_Xref As ICollection(Of Attestation_Application_Type_Role_Xref) = New HashSet(Of Attestation_Application_Type_Role_Xref)
    Public Overridable Property Certification_Requirement_Information As ICollection(Of Certification_Requirement_Information) = New HashSet(Of Certification_Requirement_Information)
    Public Overridable Property Applications As ICollection(Of Application) = New HashSet(Of Application)
    Public Overridable Property Application_History As ICollection(Of Application_History) = New HashSet(Of Application_History)
    Public Overridable Property Renewal_History_Count As ICollection(Of Renewal_History_Count) = New HashSet(Of Renewal_History_Count)

End Class
