'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Application_Uploaded_Document
    Public Property Application_Uploaded_Document_Sid As Integer
    Public Property Application_Sid As Nullable(Of Integer)
    Public Property Document_Type_Sid As Integer
    Public Property Document_Image_Store_Sid As Integer
    Public Property Active_Flg As Boolean
    Public Property Create_Date As Date
    Public Property Create_By As Integer
    Public Property Last_Update_Date As Date
    Public Property Last_Update_By As Integer
    Public Property File_Name As String
    Public Property Application_Notation_Sid As Nullable(Of Integer)

    Public Overridable Property Document_Type As Document_Type
    Public Overridable Property Application As Application
    Public Overridable Property Document_Image_Store As Document_Image_Store

End Class
