'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Attestation_Application_Type_Role_Xref
    Public Property Attestation_Application_Type_Role_Xref_Sid As Integer
    Public Property Application_Type_Sid As Integer
    Public Property Attestation_Sid As Integer
    Public Property Active_Flg As Boolean
    Public Property Start_Date As Date
    Public Property End_Date As Date
    Public Property Create_Date As Date
    Public Property Create_By As Integer
    Public Property Last_Update_Date As Date
    Public Property Last_Update_By As Integer
    Public Property Role_Sid As Integer

    Public Overridable Property Application_Type As Application_Type
    Public Overridable Property Attestation As Attestation
    Public Overridable Property MAIS_Role As MAIS_Role

End Class
