'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Category_Type
    Public Property Category_Type_Sid As Integer
    Public Property Category_Code As String
    Public Property Category_Desc As String
    Public Property Active_Flg As Boolean
    Public Property Start_Date As Date
    Public Property End_Date As Date
    Public Property Create_Date As Date
    Public Property Create_By As Integer
    Public Property Last_Update_Date As Date
    Public Property Last_Update_By As Integer

    Public Overridable Property Application_Skill_Verification As ICollection(Of Application_Skill_Verification) = New HashSet(Of Application_Skill_Verification)
    Public Overridable Property Category_Type_Skill_Type_Xref As ICollection(Of Category_Type_Skill_Type_Xref) = New HashSet(Of Category_Type_Skill_Type_Xref)
    Public Overridable Property CEUs_Renewal_Application As ICollection(Of CEUs_Renewal_Application) = New HashSet(Of CEUs_Renewal_Application)
    Public Overridable Property Role_Category_Level_Xref As ICollection(Of Role_Category_Level_Xref) = New HashSet(Of Role_Category_Level_Xref)
    Public Overridable Property Skill_Verification As ICollection(Of Skill_Verification) = New HashSet(Of Skill_Verification)
    Public Overridable Property CEUs_Renewal As ICollection(Of CEUs_Renewal) = New HashSet(Of CEUs_Renewal)

End Class
