'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Certification_Requirement_Information
    Public Property Certification_Requirement_Information_Sid As Integer
    Public Property Role_Category_Level_Sid As Integer
    Public Property Application_Type_Sid As Integer
    Public Property Requirement_Description As String
    Public Property Start_Date As Date
    Public Property End_Date As Date
    Public Property Active_Flg As Boolean
    Public Property Create_Date As Date
    Public Property Create_By As Integer
    Public Property Last_Update_Date As Date
    Public Property Last_Update_By As Integer
    Public Property Current_Role_Category_Level_Sid As Nullable(Of Integer)

    Public Overridable Property Application_Type As Application_Type
    Public Overridable Property Role_Category_Level_Xref As Role_Category_Level_Xref
    Public Overridable Property Role_Category_Level_Xref1 As Role_Category_Level_Xref

End Class
