'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class City_Information
    Public Property City_Information_Sid As Integer
    Public Property CountyID As Nullable(Of Integer)
    Public Property City As String
    Public Property StateID As Integer
    Public Property Zip As String
    Public Property Create_By As Integer
    Public Property Create_Date As Date
    Public Property Last_Update_By As Integer
    Public Property Last_Update_Date As Date

    Public Overridable Property Address1 As ICollection(Of Address1) = New HashSet(Of Address1)
    Public Overridable Property County As County
    Public Overridable Property State As State

End Class
