'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class County
    Public Property County_ID As Integer
    Public Property County_Desc As String
    Public Property County_Short_Desc As String
    Public Property County_Alias As String
    Public Property PAWS_Region_Code As String
    Public Property ODHS_Region_Code As String
    Public Property WTS_Region_Code As Nullable(Of Byte)
    Public Property County_Region_ID As Nullable(Of Integer)
    Public Property Last_Update As Date
    Public Property Last_Update_By As Integer
    Public Property Class_DBA As Integer
    Public Property County_Schedule_ID As Integer
    Public Property LIC_CountyID As String
    Public Property OID_CountyID As Nullable(Of Integer)
    Public Property OID_CountyCode As String
    Public Property CBWA_County_Code As Integer
    Public Property IO_Slots As Integer
    Public Property RFW_Slots As Integer
    Public Property COG_CountyID As Nullable(Of Integer)
    Public Property Match_Source_Flag As String
    Public Property MBS_County_Code As Nullable(Of Integer)
    Public Property Region_County_ID As Nullable(Of Integer)

    Public Overridable Property City_Information As ICollection(Of City_Information) = New HashSet(Of City_Information)

End Class
