'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DODD_Message_RN_DD_Person_Type_Xref_Xref
    Public Property DODD_Message_RN_DD_Person_Type_Xref_Xref_Sid As Integer
    Public Property RN_DD_Person_Type_XRef_SID As Integer
    Public Property DODD_Message_Sid As Integer
    Public Property Active_Flg As Boolean
    Public Property Created As Date
    Public Property CreatedBy As Integer

    Public Overridable Property DODD_Message As DODD_Message
    Public Overridable Property RN_DD_Person_Type_Xref As RN_DD_Person_Type_Xref

End Class
