'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Email1
    Public Property Email_SID As Integer
    Public Property Email_Address As String
    Public Property Created As Date
    Public Property Last_Updated As Nullable(Of Date)

    Public Overridable Property Application_Email_Xref As ICollection(Of Application_Email_Xref) = New HashSet(Of Application_Email_Xref)
    Public Overridable Property Application_Employer_Email_Xref As ICollection(Of Application_Employer_Email_Xref) = New HashSet(Of Application_Employer_Email_Xref)
    Public Overridable Property Employer_RN_DD_Person_Type_Email_Xref As ICollection(Of Employer_RN_DD_Person_Type_Email_Xref) = New HashSet(Of Employer_RN_DD_Person_Type_Email_Xref)
    Public Overridable Property RN_DD_Person_Type_Email_Xref As ICollection(Of RN_DD_Person_Type_Email_Xref) = New HashSet(Of RN_DD_Person_Type_Email_Xref)
    Public Overridable Property User_Mapping As ICollection(Of User_Mapping) = New HashSet(Of User_Mapping)
    Public Overridable Property RN_Work_Experience_Email_Xref As ICollection(Of RN_Work_Experience_Email_Xref) = New HashSet(Of RN_Work_Experience_Email_Xref)
    Public Overridable Property RN_Application_Work_Experience_Email_Xref As ICollection(Of RN_Application_Work_Experience_Email_Xref) = New HashSet(Of RN_Application_Work_Experience_Email_Xref)

End Class
