'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Employer_RN_DD_Person_Type_Xref
    Public Property Employer_RN_DD_Person_Type_Xref_Sid As Integer
    Public Property Employer_Sid As Integer
    Public Property RN_DD_Person_Type_Xref_Sid As Integer
    Public Property Employer_Type_Sid As Integer
    Public Property Provider_Contract_Number As String
    Public Property Employment_Start_Date As Date
    Public Property Employment_End_Date As Date
    Public Property CEO_Last_Name As String
    Public Property CEO_First_Name As String
    Public Property CEO_Middle_Name As String
    Public Property Supervisor_First_Name As String
    Public Property Supervisor_Last_Name As String
    Public Property Supervisor_Middle_Name As String
    Public Property Personal_Mailing_Address_Different_Flg As Boolean
    Public Property Work_Address_Same_As_Agency_Flg As Boolean
    Public Property Active_Flg As Boolean
    Public Property Create_Date As Date
    Public Property Create_By As Integer
    Public Property Last_Update_Date As Date
    Public Property Last_Update_By As Integer
    Public Property Supervisor_Start_date As Date
    Public Property Supervisor_End_date As Date

    Public Overridable Property Employer_Type As Employer_Type
    Public Overridable Property Employer As Employer
    Public Overridable Property RN_DD_Person_Type_Xref As RN_DD_Person_Type_Xref

End Class
