'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Employer
    Public Property Employer_Sid As Integer
    Public Property Employer_Name As String
    Public Property Identification_Type_Sid As Integer
    Public Property Identification_Value As String
    Public Property Active_Flg As Boolean
    Public Property Create_Date As Date
    Public Property Create_By As Integer
    Public Property Last_Update_Date As Date
    Public Property Last_Update_By As Integer

    Public Overridable Property Identification_Type As Identification_Type
    Public Overridable Property Employer_RN_DD_Person_Type_Xref As ICollection(Of Employer_RN_DD_Person_Type_Xref) = New HashSet(Of Employer_RN_DD_Person_Type_Xref)
    Public Overridable Property Employer_RN_DD_Person_Type_Address_Xref As ICollection(Of Employer_RN_DD_Person_Type_Address_Xref) = New HashSet(Of Employer_RN_DD_Person_Type_Address_Xref)
    Public Overridable Property Employer_RN_DD_Person_Type_Email_Xref As ICollection(Of Employer_RN_DD_Person_Type_Email_Xref) = New HashSet(Of Employer_RN_DD_Person_Type_Email_Xref)
    Public Overridable Property Employer_RN_DD_Person_Type_Phone_Xref As ICollection(Of Employer_RN_DD_Person_Type_Phone_Xref) = New HashSet(Of Employer_RN_DD_Person_Type_Phone_Xref)

End Class
