'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class History_Supervisor
    Public Property History_Supervisor_SID As Integer
    Public Property First_Name As String
    Public Property Last_Name As String
    Public Property Middle_name As String
    Public Property Supervisor_Start_Date As Date
    Public Property Supervisor_End_Date As Date
    Public Property Phone_SID As Nullable(Of Integer)
    Public Property Email_SID As Nullable(Of Integer)
    Public Property Created As Date

    Public Overridable Property History_Employment As ICollection(Of History_Employment) = New HashSet(Of History_Employment)

End Class
