'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class History_Employment
    Public Property History_Employment_SID As Integer
    Public Property RN_DD_Person_Type_Xref_SID As Integer
    Public Property History_Employers_SID As Integer
    Public Property History_Supervisor_SID As Integer
    Public Property History_Work_Address_Sid As Integer
    Public Property Created As Date

    Public Overridable Property History_Employers As History_Employers
    Public Overridable Property History_Supervisor As History_Supervisor
    Public Overridable Property History_Work_Address As History_Work_Address
    Public Overridable Property RN_DD_Person_Type_Xref As RN_DD_Person_Type_Xref

End Class
