'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MAIS_Role
    Public Property Role_Sid As Integer
    Public Property Role_Code As String
    Public Property Role_Desc As String
    Public Property Active_Flg As Boolean
    Public Property Start_Date As Date
    Public Property End_Date As Date
    Public Property Create_Date As Date
    Public Property Create_By As Integer
    Public Property Last_Update_Date As Date
    Public Property Last_Update_By As Integer
    Public Property Role_Priority As Nullable(Of Integer)

    Public Overridable Property Attestation_Application_Type_Role_Xref As ICollection(Of Attestation_Application_Type_Role_Xref) = New HashSet(Of Attestation_Application_Type_Role_Xref)
    Public Overridable Property Role_Category_Level_Xref As ICollection(Of Role_Category_Level_Xref) = New HashSet(Of Role_Category_Level_Xref)
    Public Overridable Property DODD_Message_MAIS_Role_XRef As ICollection(Of DODD_Message_MAIS_Role_XRef) = New HashSet(Of DODD_Message_MAIS_Role_XRef)

End Class
