'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Notation
    Public Property Notation_Sid As Integer
    Public Property RN_DD_Person_Type_Xref_Sid As Integer
    Public Property Notation_Type_Sid As Integer
    Public Property Notation_Date As Date
    Public Property Occurrence_Date As Date
    Public Property UnFlagged_Date As Nullable(Of Date)
    Public Property Person_entering_Notation As String
    Public Property Person_Title As String
    Public Property Create_Date As Date
    Public Property Create_By As Integer
    Public Property Last_Update_Date As Date
    Public Property Last_Update_By As Integer
    Public Property Application_Sid As Nullable(Of Integer)

    Public Overridable Property Notation_Type As Notation_Type
    Public Overridable Property Notation_Reason_RN_DD_Xref As ICollection(Of Notation_Reason_RN_DD_Xref) = New HashSet(Of Notation_Reason_RN_DD_Xref)
    Public Overridable Property RN_DD_Person_Type_Xref As RN_DD_Person_Type_Xref

End Class
