'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Notation_Type
    Public Property Notation_Type_Sid As Integer
    Public Property Notation_Code As String
    Public Property Notation_Desc As String
    Public Property Active_Flg As Boolean
    Public Property Start_Date As Date
    Public Property End_Date As Date
    Public Property Create_Date As Date
    Public Property Create_By As Integer
    Public Property Last_Update_Date As Date
    Public Property Last_Update_By As Integer

    Public Overridable Property Notation_Reason_Xref As ICollection(Of Notation_Reason_Xref) = New HashSet(Of Notation_Reason_Xref)
    Public Overridable Property Notations As ICollection(Of Notation) = New HashSet(Of Notation)

End Class
