'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Person_Course_Xref
    Public Property Person_Course_Xref_Sid As Integer
    Public Property Role_RN_DD_Personnel_Xref_Sid As Integer
    Public Property Course_Sid As Integer
    Public Property Active_Flg As Boolean
    Public Property Create_Date As Date
    Public Property Create_By As Integer
    Public Property Last_Update_Date As Date
    Public Property Last_Update_By As Integer

    Public Overridable Property Person_Course_Session_Xref As ICollection(Of Person_Course_Session_Xref) = New HashSet(Of Person_Course_Session_Xref)
    Public Overridable Property Role_RN_DD_Personnel_Xref As Role_RN_DD_Personnel_Xref
    Public Overridable Property Course As Course

End Class
