'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Phone_Number
    Public Property Phone_Number_SID As Integer
    Public Property Phone_Number1 As String
    Public Property Created As Date
    Public Property Last_Updated As Nullable(Of Date)

    Public Overridable Property Application_Phone_Xref As ICollection(Of Application_Phone_Xref) = New HashSet(Of Application_Phone_Xref)
    Public Overridable Property Application_Employer_Phone_Xref As ICollection(Of Application_Employer_Phone_Xref) = New HashSet(Of Application_Employer_Phone_Xref)
    Public Overridable Property RN_DD_Person_Type_Phone_Xref As ICollection(Of RN_DD_Person_Type_Phone_Xref) = New HashSet(Of RN_DD_Person_Type_Phone_Xref)
    Public Overridable Property RN_Work_Experience_Phone_Xref As ICollection(Of RN_Work_Experience_Phone_Xref) = New HashSet(Of RN_Work_Experience_Phone_Xref)
    Public Overridable Property RN_Application_Work_Experience_Phone_Xref As ICollection(Of RN_Application_Work_Experience_Phone_Xref) = New HashSet(Of RN_Application_Work_Experience_Phone_Xref)
    Public Overridable Property Employer_RN_DD_Person_Type_Phone_Xref As ICollection(Of Employer_RN_DD_Person_Type_Phone_Xref) = New HashSet(Of Employer_RN_DD_Person_Type_Phone_Xref)

End Class
