'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Renewal_History_Count
    Public Property Renewal_History_Count_Sid As Integer
    Public Property RN_DD_Person_Type_Xref_Sid As Integer
    Public Property Renewal_Count As Integer
    Public Property Create_Date As Date
    Public Property Create_By As Integer
    Public Property Last_Update_Date As Date
    Public Property Last_Update_By As Integer
    Public Property Role_Category_Level_sid As Integer
    Public Property Application_type_SId As Nullable(Of Integer)

    Public Overridable Property Application_Type As Application_Type
    Public Overridable Property RN_DD_Person_Type_Xref As RN_DD_Person_Type_Xref
    Public Overridable Property Role_Category_Level_Xref As Role_Category_Level_Xref

End Class
