'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RN_Application_Work_Experience_Phone_Xref
    Public Property RN_Application_Work_Experience_Phone_Xref_Sid As Integer
    Public Property RN_Application_Work_Experience_Sid As Integer
    Public Property Phone_Sid As Integer
    Public Property Contact_Type_Sid As Integer
    Public Property Active_Flg As Boolean
    Public Property Create_Date As Date
    Public Property Create_By As Integer
    Public Property Last_Update_Date As Date
    Public Property Last_Update_By As Integer

    Public Overridable Property Contact_Type As Contact_Type
    Public Overridable Property RN_Application_Work_Experience As RN_Application_Work_Experience
    Public Overridable Property Phone_Number As Phone_Number

End Class
