'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RN_Application
    Public Property Application_Sid As Integer
    Public Property RNLicense_Number As String
    Public Property First_Name As String
    Public Property Last_Name As String
    Public Property Middle_Name As String
    Public Property Create_Date As Date
    Public Property Create_By As Integer
    Public Property Last_Updated_Date As Date
    Public Property Last_Update_By As Integer
    Public Property Date_Of_Original_Issuance As Date
    Public Property Gender As String

    Public Overridable Property Application As Application

End Class
