'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RN_Secretary_Association
    Public Property RN_Secretary_Association_Sid As Integer
    Public Property User_Mapping_Sid As Integer
    Public Property Comments As String
    Public Property Active_Flg As Boolean
    Public Property Create_Date As Date
    Public Property Create_By As Integer
    Public Property Last_Update_Date As Date
    Public Property Last_Update_By As Integer
    Public Property RN_Sid As Integer

    Public Overridable Property RN As RN
    Public Overridable Property User_Mapping As User_Mapping

End Class
