'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Session_Address_Xref
    Public Property Session_Address_Xref_Sid As Integer
    Public Property Session_Sid As Integer
    Public Property Address_Sid As Integer
    Public Property Address_Type_Sid As Integer
    Public Property Active_Flg As Boolean
    Public Property Start_Date As Date
    Public Property End_Date As Date
    Public Property Create_Date As Date
    Public Property Create_By As Integer
    Public Property Last_Update_Date As Date
    Public Property Last_Update_By As Integer

    Public Overridable Property Address_Type As Address_Type
    Public Overridable Property Session As Session
    Public Overridable Property Address As Address1

End Class
