'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Skill_Verification_Type_CheckList_Xref
    Public Property Skill_Verification_Type_CheckList_Xref_Sid As Integer
    Public Property Skill_Verification_Skill_Type_Xref_Sid As Integer
    Public Property Skill_CheckList_Sid As Integer
    Public Property Verification_Date As Date
    Public Property Verified_Person_Name As String
    Public Property Verified_Person_Title As String
    Public Property Active_Flg As Boolean
    Public Property Create_Date As Date
    Public Property Create_By As Integer
    Public Property Last_Update_Date As Date
    Public Property Last_Update_By As Integer

    Public Overridable Property Skill_CheckList As Skill_CheckList
    Public Overridable Property Skill_Verification_Skill_Type_Xref As Skill_Verification_Skill_Type_Xref

End Class
