'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Skill_CheckList
    Public Property Skill_CheckList_Sid As Integer
    Public Property Skill_CheckList_Code As String
    Public Property Skill_CheckList_Desc As String
    Public Property Active_Flg As Boolean
    Public Property Start_Date As Date
    Public Property End_Date As Date
    Public Property Create_Date As Date
    Public Property Create_By As Integer
    Public Property Last_Update_Date As Date
    Public Property Last_Update_By As Integer

    Public Overridable Property Application_Skill_Type_CheckList_Xref As ICollection(Of Application_Skill_Type_CheckList_Xref) = New HashSet(Of Application_Skill_Type_CheckList_Xref)
    Public Overridable Property Skill_Type_Skill_CheckList_Xref As ICollection(Of Skill_Type_Skill_CheckList_Xref) = New HashSet(Of Skill_Type_Skill_CheckList_Xref)
    Public Overridable Property Skill_Verification_Type_CheckList_Xref As ICollection(Of Skill_Verification_Type_CheckList_Xref) = New HashSet(Of Skill_Verification_Type_CheckList_Xref)

End Class
