'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class User_Mapping
    Public Property User_Mapping_Sid As Integer
    Public Property UserID As Integer
    Public Property Portal_User_Role As String
    Public Property First_Name As String
    Public Property Last_Name As String
    Public Property Middle_Name As String
    Public Property Start_Date As Date
    Public Property End_Date As Date
    Public Property Active_Flg As Boolean
    Public Property Create_Date As Date
    Public Property Create_By As Integer
    Public Property Last_Update_Date As Date
    Public Property Last_Update_By As Integer
    Public Property Email_Sid As Nullable(Of Integer)
    Public Property Is_Secretary_Flg As Boolean
    Public Property User_Code As String

    Public Overridable Property RN_Secretary_Association As ICollection(Of RN_Secretary_Association) = New HashSet(Of RN_Secretary_Association)
    Public Overridable Property Email As Email1
    Public Overridable Property User_RN_Mapping As User_RN_Mapping

End Class
