'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace UserService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UserInfo", [Namespace]:="http://schemas.datacontract.org/2004/07/DODDSVC.DTO"),  _
     System.SerializableAttribute()>  _
    Partial Public Class UserInfo
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmailAddressField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FirstNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FullNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LastNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserIdField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EmailAddress() As String
            Get
                Return Me.EmailAddressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmailAddressField, value) <> true) Then
                    Me.EmailAddressField = value
                    Me.RaisePropertyChanged("EmailAddress")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FirstName() As String
            Get
                Return Me.FirstNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FirstNameField, value) <> true) Then
                    Me.FirstNameField = value
                    Me.RaisePropertyChanged("FirstName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FullName() As String
            Get
                Return Me.FullNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FullNameField, value) <> true) Then
                    Me.FullNameField = value
                    Me.RaisePropertyChanged("FullName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LastName() As String
            Get
                Return Me.LastNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LastNameField, value) <> true) Then
                    Me.LastNameField = value
                    Me.RaisePropertyChanged("LastName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserCode() As String
            Get
                Return Me.UserCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserCodeField, value) <> true) Then
                    Me.UserCodeField = value
                    Me.RaisePropertyChanged("UserCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserId() As Integer
            Get
                Return Me.UserIdField
            End Get
            Set
                If (Me.UserIdField.Equals(value) <> true) Then
                    Me.UserIdField = value
                    Me.RaisePropertyChanged("UserId")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UserType", [Namespace]:="http://schemas.datacontract.org/2004/07/DODDSVC.Enums")>  _
    Public Enum UserType As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ODMRDD_DITS = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ODRMDD_CentralOffice = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        CountyBoard = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        COG = 4
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Provider = 5
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Other = 99
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ProviderType", [Namespace]:="http://schemas.datacontract.org/2004/07/DODDSVC.Enums")>  _
    Public Enum ProviderType As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Agency = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Individual = 2
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UserReference", [Namespace]:="http://schemas.datacontract.org/2004/07/DODDSVC"),  _
     System.SerializableAttribute()>  _
    Partial Public Class UserReference
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private AdminUserIDField As String
        
        Private address1Field As String
        
        Private cityField As String
        
        Private cntField As String
        
        Private effdateField As Date
        
        Private emailField As String
        
        Private enddateField As Date
        
        Private expirationDateField As Date
        
        Private f4Field As String
        
        Private f5Field As String
        
        Private fNameField As String
        
        Private groupIdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private hasErrorField As Boolean
        
        Private lNameField As String
        
        Private mNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private messagesField As String
        
        Private passwordField As String
        
        Private phonegroupidField As String
        
        Private roleidField As String
        
        Private stateField As String
        
        Private statusField As String
        
        Private systemIdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private userCodeField As String
        
        Private userIdField As String
        
        Private zipcodeField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property AdminUserID() As String
            Get
                Return Me.AdminUserIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AdminUserIDField, value) <> true) Then
                    Me.AdminUserIDField = value
                    Me.RaisePropertyChanged("AdminUserID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property address1() As String
            Get
                Return Me.address1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.address1Field, value) <> true) Then
                    Me.address1Field = value
                    Me.RaisePropertyChanged("address1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property city() As String
            Get
                Return Me.cityField
            End Get
            Set
                If (Object.ReferenceEquals(Me.cityField, value) <> true) Then
                    Me.cityField = value
                    Me.RaisePropertyChanged("city")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property cnt() As String
            Get
                Return Me.cntField
            End Get
            Set
                If (Object.ReferenceEquals(Me.cntField, value) <> true) Then
                    Me.cntField = value
                    Me.RaisePropertyChanged("cnt")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property effdate() As Date
            Get
                Return Me.effdateField
            End Get
            Set
                If (Me.effdateField.Equals(value) <> true) Then
                    Me.effdateField = value
                    Me.RaisePropertyChanged("effdate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property email() As String
            Get
                Return Me.emailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.emailField, value) <> true) Then
                    Me.emailField = value
                    Me.RaisePropertyChanged("email")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property enddate() As Date
            Get
                Return Me.enddateField
            End Get
            Set
                If (Me.enddateField.Equals(value) <> true) Then
                    Me.enddateField = value
                    Me.RaisePropertyChanged("enddate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property expirationDate() As Date
            Get
                Return Me.expirationDateField
            End Get
            Set
                If (Me.expirationDateField.Equals(value) <> true) Then
                    Me.expirationDateField = value
                    Me.RaisePropertyChanged("expirationDate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property f4() As String
            Get
                Return Me.f4Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.f4Field, value) <> true) Then
                    Me.f4Field = value
                    Me.RaisePropertyChanged("f4")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property f5() As String
            Get
                Return Me.f5Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.f5Field, value) <> true) Then
                    Me.f5Field = value
                    Me.RaisePropertyChanged("f5")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property fName() As String
            Get
                Return Me.fNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.fNameField, value) <> true) Then
                    Me.fNameField = value
                    Me.RaisePropertyChanged("fName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property groupId() As String
            Get
                Return Me.groupIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.groupIdField, value) <> true) Then
                    Me.groupIdField = value
                    Me.RaisePropertyChanged("groupId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property hasError() As Boolean
            Get
                Return Me.hasErrorField
            End Get
            Set
                If (Me.hasErrorField.Equals(value) <> true) Then
                    Me.hasErrorField = value
                    Me.RaisePropertyChanged("hasError")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property lName() As String
            Get
                Return Me.lNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.lNameField, value) <> true) Then
                    Me.lNameField = value
                    Me.RaisePropertyChanged("lName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property mName() As String
            Get
                Return Me.mNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.mNameField, value) <> true) Then
                    Me.mNameField = value
                    Me.RaisePropertyChanged("mName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property messages() As String
            Get
                Return Me.messagesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.messagesField, value) <> true) Then
                    Me.messagesField = value
                    Me.RaisePropertyChanged("messages")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                If (Object.ReferenceEquals(Me.passwordField, value) <> true) Then
                    Me.passwordField = value
                    Me.RaisePropertyChanged("password")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property phonegroupid() As String
            Get
                Return Me.phonegroupidField
            End Get
            Set
                If (Object.ReferenceEquals(Me.phonegroupidField, value) <> true) Then
                    Me.phonegroupidField = value
                    Me.RaisePropertyChanged("phonegroupid")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property roleid() As String
            Get
                Return Me.roleidField
            End Get
            Set
                If (Object.ReferenceEquals(Me.roleidField, value) <> true) Then
                    Me.roleidField = value
                    Me.RaisePropertyChanged("roleid")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property state() As String
            Get
                Return Me.stateField
            End Get
            Set
                If (Object.ReferenceEquals(Me.stateField, value) <> true) Then
                    Me.stateField = value
                    Me.RaisePropertyChanged("state")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property status() As String
            Get
                Return Me.statusField
            End Get
            Set
                If (Object.ReferenceEquals(Me.statusField, value) <> true) Then
                    Me.statusField = value
                    Me.RaisePropertyChanged("status")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property systemId() As String
            Get
                Return Me.systemIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.systemIdField, value) <> true) Then
                    Me.systemIdField = value
                    Me.RaisePropertyChanged("systemId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property userCode() As String
            Get
                Return Me.userCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.userCodeField, value) <> true) Then
                    Me.userCodeField = value
                    Me.RaisePropertyChanged("userCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property userId() As String
            Get
                Return Me.userIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.userIdField, value) <> true) Then
                    Me.userIdField = value
                    Me.RaisePropertyChanged("userId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property zipcode() As String
            Get
                Return Me.zipcodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.zipcodeField, value) <> true) Then
                    Me.zipcodeField = value
                    Me.RaisePropertyChanged("zipcode")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="EmailReference", [Namespace]:="http://schemas.datacontract.org/2004/07/DODDSVC"),  _
     System.SerializableAttribute()>  _
    Partial Public Class EmailReference
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BodyField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReplyToField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SendFromField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SendToField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SubjectField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private sendCCField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Body() As String
            Get
                Return Me.BodyField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BodyField, value) <> true) Then
                    Me.BodyField = value
                    Me.RaisePropertyChanged("Body")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ReplyTo() As String
            Get
                Return Me.ReplyToField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ReplyToField, value) <> true) Then
                    Me.ReplyToField = value
                    Me.RaisePropertyChanged("ReplyTo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SendFrom() As String
            Get
                Return Me.SendFromField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SendFromField, value) <> true) Then
                    Me.SendFromField = value
                    Me.RaisePropertyChanged("SendFrom")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SendTo() As String
            Get
                Return Me.SendToField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SendToField, value) <> true) Then
                    Me.SendToField = value
                    Me.RaisePropertyChanged("SendTo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Subject() As String
            Get
                Return Me.SubjectField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SubjectField, value) <> true) Then
                    Me.SubjectField = value
                    Me.RaisePropertyChanged("Subject")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property sendCC() As String
            Get
                Return Me.sendCCField
            End Get
            Set
                If (Object.ReferenceEquals(Me.sendCCField, value) <> true) Then
                    Me.sendCCField = value
                    Me.RaisePropertyChanged("sendCC")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="UserService.IUserService")>  _
    Public Interface IUserService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IUserService/GetUsersByRole", ReplyAction:="http://tempuri.org/IUserService/GetUsersByRoleResponse")>  _
        Function GetUsersByRole(ByVal strRole() As String) As UserService.UserInfo()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IUserService/GetUsersByUserGroup", ReplyAction:="http://tempuri.org/IUserService/GetUsersByUserGroupResponse")>  _
        Function GetUsersByUserGroup(ByVal userGroupId As Integer) As UserService.UserInfo()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IUserService/GetUsersByUserType", ReplyAction:="http://tempuri.org/IUserService/GetUsersByUserTypeResponse")>  _
        Function GetUsersByUserType(ByVal userType As UserService.UserType) As UserService.UserInfo()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IUserService/GetUsersByProviderType", ReplyAction:="http://tempuri.org/IUserService/GetUsersByProviderTypeResponse")>  _
        Function GetUsersByProviderType(ByVal providerType As UserService.ProviderType) As UserService.UserInfo()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IUserService/GetProviderUserInfo", ReplyAction:="http://tempuri.org/IUserService/GetProviderUserInfoResponse")>  _
        Function GetProviderUserInfo(ByVal contractNumber As String) As UserService.UserInfo()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IUserService/GetBillingAgentUserInfo", ReplyAction:="http://tempuri.org/IUserService/GetBillingAgentUserInfoResponse")>  _
        Function GetBillingAgentUserInfo(ByVal contractNumber As String) As UserService.UserInfo()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IUserService/GetUserIdByUserCode", ReplyAction:="http://tempuri.org/IUserService/GetUserIdByUserCodeResponse")>  _
        Function GetUserIdByUserCode(ByVal strUserCode As String) As Long
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IUserService/CreateUser", ReplyAction:="http://tempuri.org/IUserService/CreateUserResponse")>  _
        Function CreateUser(ByRef createUserData As UserService.UserReference) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IUserService/CreatePassword", ReplyAction:="http://tempuri.org/IUserService/CreatePasswordResponse")>  _
        Function CreatePassword() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IUserService/SendEmail", ReplyAction:="http://tempuri.org/IUserService/SendEmailResponse")>  _
        Function SendEmail(ByVal emailParams As UserService.EmailReference) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IUserService/CognosChangeUser", ReplyAction:="http://tempuri.org/IUserService/CognosChangeUserResponse")>  _
        Function CognosChangeUser(ByVal UserData As UserService.UserReference) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IUserService/CognosAddUser", ReplyAction:="http://tempuri.org/IUserService/CognosAddUserResponse")>  _
        Function CognosAddUser(ByVal UserData As UserService.UserReference) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IUserService/CognosDisableUserAcct", ReplyAction:="http://tempuri.org/IUserService/CognosDisableUserAcctResponse")>  _
        Function CognosDisableUserAcct(ByVal userCode As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IUserService/CognosEnableUserAcct", ReplyAction:="http://tempuri.org/IUserService/CognosEnableUserAcctResponse")>  _
        Function CognosEnableUserAcct(ByVal userCode As String) As String
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IUserServiceChannel
        Inherits UserService.IUserService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class UserServiceClient
        Inherits System.ServiceModel.ClientBase(Of UserService.IUserService)
        Implements UserService.IUserService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetUsersByRole(ByVal strRole() As String) As UserService.UserInfo() Implements UserService.IUserService.GetUsersByRole
            Return MyBase.Channel.GetUsersByRole(strRole)
        End Function
        
        Public Function GetUsersByUserGroup(ByVal userGroupId As Integer) As UserService.UserInfo() Implements UserService.IUserService.GetUsersByUserGroup
            Return MyBase.Channel.GetUsersByUserGroup(userGroupId)
        End Function
        
        Public Function GetUsersByUserType(ByVal userType As UserService.UserType) As UserService.UserInfo() Implements UserService.IUserService.GetUsersByUserType
            Return MyBase.Channel.GetUsersByUserType(userType)
        End Function
        
        Public Function GetUsersByProviderType(ByVal providerType As UserService.ProviderType) As UserService.UserInfo() Implements UserService.IUserService.GetUsersByProviderType
            Return MyBase.Channel.GetUsersByProviderType(providerType)
        End Function
        
        Public Function GetProviderUserInfo(ByVal contractNumber As String) As UserService.UserInfo() Implements UserService.IUserService.GetProviderUserInfo
            Return MyBase.Channel.GetProviderUserInfo(contractNumber)
        End Function
        
        Public Function GetBillingAgentUserInfo(ByVal contractNumber As String) As UserService.UserInfo() Implements UserService.IUserService.GetBillingAgentUserInfo
            Return MyBase.Channel.GetBillingAgentUserInfo(contractNumber)
        End Function
        
        Public Function GetUserIdByUserCode(ByVal strUserCode As String) As Long Implements UserService.IUserService.GetUserIdByUserCode
            Return MyBase.Channel.GetUserIdByUserCode(strUserCode)
        End Function
        
        Public Function CreateUser(ByRef createUserData As UserService.UserReference) As String Implements UserService.IUserService.CreateUser
            Return MyBase.Channel.CreateUser(createUserData)
        End Function
        
        Public Function CreatePassword() As String Implements UserService.IUserService.CreatePassword
            Return MyBase.Channel.CreatePassword
        End Function
        
        Public Function SendEmail(ByVal emailParams As UserService.EmailReference) As String Implements UserService.IUserService.SendEmail
            Return MyBase.Channel.SendEmail(emailParams)
        End Function
        
        Public Function CognosChangeUser(ByVal UserData As UserService.UserReference) As String Implements UserService.IUserService.CognosChangeUser
            Return MyBase.Channel.CognosChangeUser(UserData)
        End Function
        
        Public Function CognosAddUser(ByVal UserData As UserService.UserReference) As String Implements UserService.IUserService.CognosAddUser
            Return MyBase.Channel.CognosAddUser(UserData)
        End Function
        
        Public Function CognosDisableUserAcct(ByVal userCode As String) As String Implements UserService.IUserService.CognosDisableUserAcct
            Return MyBase.Channel.CognosDisableUserAcct(userCode)
        End Function
        
        Public Function CognosEnableUserAcct(ByVal userCode As String) As String Implements UserService.IUserService.CognosEnableUserAcct
            Return MyBase.Channel.CognosEnableUserAcct(userCode)
        End Function
    End Class
End Namespace
