'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace CBOSSWebService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="NotFoundFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Cboss.DataTransferTokenizer.Application.P"& _ 
        "resentation"),  _
     System.SerializableAttribute()>  _
    Partial Public Class NotFoundFault
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MessageField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Message() As String
            Get
                Return Me.MessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageField, value) <> true) Then
                    Me.MessageField = value
                    Me.RaisePropertyChanged("Message")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.cboss.com/DataTransferTokenizer/1.0", ConfigurationName:="CBOSSWebService.Tokenization")>  _
    Public Interface Tokenization
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.cboss.com/DataTransferTokenizer/1.0/Tokenization/Detokenize", ReplyAction:="http://www.cboss.com/DataTransferTokenizer/1.0/Tokenization/DetokenizeResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(CBOSSWebService.NotFoundFault), Action:="http://www.cboss.com/DataTransferTokenizer/1.0/Tokenization/DetokenizeNotFoundFau"& _ 
            "ltFault", Name:="NotFoundFault", [Namespace]:="http://schemas.datacontract.org/2004/07/Cboss.DataTransferTokenizer.Application.P"& _ 
            "resentation")>  _
        Function Detokenize(ByVal token As System.Guid) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.cboss.com/DataTransferTokenizer/1.0/Tokenization/Tokenize", ReplyAction:="http://www.cboss.com/DataTransferTokenizer/1.0/Tokenization/TokenizeResponse")>  _
        Function Tokenize(ByVal data As String) As System.Guid
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface TokenizationChannel
        Inherits CBOSSWebService.Tokenization, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class TokenizationClient
        Inherits System.ServiceModel.ClientBase(Of CBOSSWebService.Tokenization)
        Implements CBOSSWebService.Tokenization
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Detokenize(ByVal token As System.Guid) As String Implements CBOSSWebService.Tokenization.Detokenize
            Return MyBase.Channel.Detokenize(token)
        End Function
        
        Public Function Tokenize(ByVal data As String) As System.Guid Implements CBOSSWebService.Tokenization.Tokenize
            Return MyBase.Channel.Tokenize(data)
        End Function
    End Class
End Namespace
